travis:
  secure:
    BINSTAR_TOKEN: wyFgivKrJtVfSQjuWYlQ7NDkU9KlIhSG1E1TuAxbzT4v8roaZKvVZofbrnsyJQpfzqsmwTFSiyTGCKFIYsLRo+dZNmz4jFUb3ut6pwIrjA5pPKFMwLTttbCQdWznRHm09KFCdQ99lf3qvh2hY6vo7chUXUo1/8ZYpsH4Y2f80XJy8fOTE2itipFkpjyLKP70DWaH67H5bdo7bDetxcE5Oas4pmL2UB1MkpCDd1ZBYJQ/PYkdddHlvLcrirywmrnLAtT+DMHbhO8/6vM+RudkbWx/41XCPdt8H16nTeNBGwP8Je7WLVYKJBm7Xnpxd0wAaJ2Fa4O1qcPxyL+oqb+b85lkUVkn6qwWTprXRijn8mlgWDYjONjtk46Nx+dtJDjLBPswv79ddaLyd5KXkuu1MzgcHIp7rDDOSMQjnBZi3dfG7EJoIXHQrRllliljPJaX8S5nPZXgPscyroZzpHkoHjq1/MawEGjkQaQ4oeqzteNhalRuzkdynIWcCZGgYU8wtL/Xb9jt58IffjKEPVqoCjmUcOjVLQkW5M3vq3wGCCrgX0L9JXjAwIdfq6PSY9vdA6V6z4ay3F7BFS31q3hPELN1+HFICwtuDeYbcxEq6vxsxSmhGnw0tYDvi6JCmbyeg4/hJFjvYzXYioK50tYrTgdm++cq0AlBHKaRuC109DM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
